// <auto-generated />
using System;
using Babysitter1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Babysitter1.Migrations
{
    [DbContext(typeof(BabysitterContext))]
    partial class BabysitterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Babysitter1.Models.DefaultSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Evening");

                    b.Property<decimal>("LateNite");

                    b.Property<string>("MaxTime");

                    b.Property<string>("MinTime");

                    b.Property<decimal>("Standard");

                    b.HasKey("Id");

                    b.ToTable("DefaultSystem");
                });

            modelBuilder.Entity("Babysitter1.Models.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bedtime");

                    b.Property<bool>("Cash");

                    b.Property<string>("ContactEmail");

                    b.Property<string>("ContactPhone");

                    b.Property<string>("HomePhone");

                    b.Property<string>("Name");

                    b.Property<bool>("PartialPay");

                    b.HasKey("Id");

                    b.ToTable("Family");
                });

            modelBuilder.Entity("Babysitter1.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EndTime");

                    b.Property<int?>("FamilyId");

                    b.Property<DateTime>("JobDate");

                    b.Property<bool>("Paid");

                    b.Property<string>("StartTime");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("Babysitter1.Models.Kid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Age");

                    b.Property<string>("Bedtime");

                    b.Property<int?>("FamilyId");

                    b.Property<int?>("JobId");

                    b.Property<string>("Name");

                    b.Property<string>("Note");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("JobId");

                    b.ToTable("Kid");
                });

            modelBuilder.Entity("Babysitter1.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<int>("EarlyHours");

                    b.Property<int>("EveningHours");

                    b.Property<string>("FamilyName");

                    b.Property<DateTime>("JobDate");

                    b.Property<int>("LateHours");

                    b.Property<int>("TotalHours");

                    b.HasKey("Id");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Babysitter1.Models.Job", b =>
                {
                    b.HasOne("Babysitter1.Models.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId");
                });

            modelBuilder.Entity("Babysitter1.Models.Kid", b =>
                {
                    b.HasOne("Babysitter1.Models.Family", "Family")
                        .WithMany("Kids")
                        .HasForeignKey("FamilyId");

                    b.HasOne("Babysitter1.Models.Job")
                        .WithMany("Kids")
                        .HasForeignKey("JobId");
                });
#pragma warning restore 612, 618
        }
    }
}
